# Generated by Django 5.0.1 on 2024-02-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer'),
        ),
    ]
